version: 1
formatters:
  default:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
  file:
    class: logging.FileHandler
    formatter: default
    filename: app.log
  console:
    class: logging.StreamHandler
    formatter: default
loggers:
  uvicorn:
    handlers: [file, console]
    level: DEBUG
    propagate: no
  uvicorn.error:
    handlers: [file, console]
    level: ERROR
    propagate: no
  uvicorn.access:
    handlers: [file, console]
    level: INFO
    propagate: no
root:
  handlers: [file, console]
  level: DEBUG
